export const DEFAULT_TEST_BY_CONDITION: Readonly<Record<string, string>> = {
  akromegalie: "igf1-acromegaly",
  "cushing-syndrom-hyperkortisolismus": "dst-1mg",
  "morbus-basedow": "trab-graves",
  "medullares-schilddrusenkarzinom": "basal-calcitonin-thyroid-nodule",
  nebenniereninsuffizienz: "acth-stimulation-250",
  "phaochromozytom-paragangliom": "metanephrines-plasma",
  "primarer-hyperaldosteronismus": "arr",
  zoliakie: "ttg-iga-celiac",
  herzinsuffizienz: "ntprobnp",
  "tiefe-venenthrombose": "d-dimer-dvt",
  lungenembolie: "d-dimer-pe",
  "chronische-nierenkrankheit": "egfr-creatinine-ckd",
  glomerulonephritis: "urine-sediment-glomerulonephritis",
  "obstruktive-koronare-herzkrankheit": "coronary-ct-angiography-cad",
  "akutes-koronarsyndrom-myokardschaden": "high-sensitivity-troponin-t-acs",
  "primarer-hyperparathyreoidismus": "calcium-pth-phpt",
  "renale-arterienstenose": "renal-artery-duplex-ras",
  "schilddrusenknoten-malignitatsrisiko": "thyroid-fna-bethesda",
};
