export const DEFAULT_TEST_BY_CONDITION: Readonly<Record<string, string>> = {
  akromegalie: "igf1-acromegaly",
  "cushing-syndrom-hyperkortisolismus": "dst-1mg",
  "morbus-basedow": "trab-graves",
  "medullares-schilddrusenkarzinom": "basal-calcitonin-thyroid-nodule",
  nebenniereninsuffizienz: "primary-ai-context",
  schilddrusenfunktionsstorung: "thyroid-function-reflex",
  hyperprolaktinamie: "prolactin-context",
  "mannlicher-hypogonadismus": "testosterone-confirmation",
  "osteoporose-frakturrisiko": "dxa-fracture-context",
  "hyperandrogenismus-zyklusstorung": "androgen-cycle-context",
  "diabetes-diagnostik": "glucose-hba1c-confirmation",
  "phaochromozytom-paragangliom": "metanephrines-plasma",
  "primarer-hyperaldosteronismus": "arr",
  zoliakie: "ttg-iga-celiac",
  herzinsuffizienz: "ntprobnp",
  "tiefe-venenthrombose": "d-dimer-dvt",
  lungenembolie: "d-dimer-pe",
  "chronische-nierenkrankheit": "egfr-creatinine-ckd",
  glomerulonephritis: "urine-sediment-glomerulonephritis",
  "obstruktive-koronare-herzkrankheit": "coronary-ct-angiography-cad",
  "akutes-koronarsyndrom-myokardschaden": "high-sensitivity-troponin-t-acs",
  "primarer-hyperparathyreoidismus": "calcium-pth-phpt",
  "renale-arterienstenose": "renal-artery-duplex-ras",
  "schilddrusenknoten-malignitatsrisiko": "thyroid-fna-bethesda",
};
